@echo off
echo Starting Kiwi Photo Library...

echo Starting backend server...
start "Backend Server" cmd /k "cd server && npm start"

echo Waiting for backend to start...
timeout /t 3 /nobreak > nul

echo Starting frontend server...
start "Frontend Server" cmd /k "npm run dev"

echo Both servers are starting...
echo Frontend: http://localhost:3000
echo Backend: http://localhost:3001
echo.
echo Press any key to close this window...
pause > nul 